[package]
name = "base64-stream"
version = "1.0.7"
edition = "2018"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/base64-stream"
homepage = "https://magiclen.org/base64-stream"
keywords = ["base64", "stream", "file", "reader", "writer"]
categories = ["encoding"]
description= "To encode/decode large data with the standard Base64 encoding."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/base64-stream"
branch = "master"

[dependencies]
base64 = "0.10"

[dependencies.educe]
version = ">=0.4.0"
features = ["Debug"]
default-features = false